### ISSUE TITLE
"failed to open for reading (No such file or directory)" error

### ISSUE THREAD

**Issue by grandoba** [ialzugaray/haste#3]
```sh
~/temp_git/haste/build$ cmake .. -DCMAKE_BUILD_TYPE=Release -DGUI=false
CMake Error at cmake_modules/FindEigen3.cmake:43 (file):
  file failed to open for reading (No such file or directory):

    /mypath/haste/thirdparty/eigen/Eigen/src/Core/util/Macros.h
Call Stack (most recent call first):
  cmake_modules/FindEigen3.cmake:69 (_eigen3_check_version)
  CMakeLists.txt:19 (find_package)


-- Found Eigen headers in: /home/suhu/temp_git/haste/thirdparty/eigen
-DGUI=false. No GUI will be compiled.
-- Configuring incomplete, errors occurred!
See also "/mypath/haste/build/CMakeFiles/CMakeOutput.log".
```

It seems you have a symbolic link, so it would be preferred if you also explained how you created the link in the instructions :)

The following worked out for me
```sh
cd /mypath/hast/thirdparty/eigen
ln -s /path/to/eigen3/Eigen/ . 
```

**Comment by ialzugaray** [comment]
Hi, 
Thanks for your comment. Unfortunately, I am unable to reproduce your bug. At the moment the Eigen repo we are using as a submodule  (https://gitlab.com/libeigen/eigen.git) has the specified relative path that your missing (eigen/Eigen/src...) so that no symbolic link should be necessary.

When you create the symbolic link, do you link it to your system-installed Eigen (this is the `/path/to/eigen3/Eigen/` you mention)? Could you verify whether when you use  `git submodule update --init --recursive` then  `thirdparty/eigen/` is correctly populated?

**Comment by grandoba** [comment]
Thank you for your reply. 

I admit I didn't read the instructions properly :(

And yeah `git submodule update --init --recurse` worked :+1: 

Thanks again
