### ISSUE TITLE
Errors on Eigen and other files

### ISSUE THREAD

**Issue by lizeyu000** [ialzugaray/haste#4]
Hello! I am interested in your wonderful event tracking algorithm, However, I did everything needed for compiling,including "git submodule update --init --recursive",  It has the following errors, which come from Eigen. Could you specify the version of Eigen you used?

haste/thirdparty/eigen/Eigen/src/Core/util/Meta.h:504:25: error: ‘invoke_result’ in namespace ‘std’ does not name a template type
   typedef typename std::invoke_result<F, ArgTypes...>::type type1;
                         ^
haste/thirdparty/eigen/Eigen/src/Core/util/Meta.h:504:38: error: expected unqualified-id before ‘<’ token
   typedef typename std::invoke_result<F, ArgTypes...>::type type1;

I also changed a different version of Eigen,The problem seems solved. But another compiling error is:

In file included from /HASTE/haste/include/haste/app/tracking.hpp:8:0,
                 from /HASTE/haste/include/haste/app/command_parser.hpp:7,
                 from /HASTE/haste/include/haste/app_gui.hpp:5,
                 from /ASTE/haste/src/tracking_app_gui.cpp:4:
/home/haste/include/haste/aux/aux.hpp: In function ‘std::vector<std::__cxx11::basic_string<char> > haste::splitString(const string&, char)’:
/home/lizeyu/HASTE/haste/include/haste/aux/aux.hpp:18:63: error: invalid use of ‘void’
   while (std::getline(iss, item, delim)) { ret.emplace_back() = item; }

At your convenience , could you give me some hints about the problem?

Thank you!

**Comment by ialzugaray** [comment]
Hi, thanks for your interest in our algorithms. 

The required Eigen version is specified in the README.md (version >= 3.4):
https://github.com/ialzugaray/haste/blob/955c80acf6256d1d4fead22e6b11b8e351b34f53/README.md#L70
Since this one is not originally distributed with Ubuntu 18.04, we also ship it in the `thirdparty/` folder. The path seems to be correct from the error you report, so please make sure you are not linking against symbols from the `thirdparty/` folder using an outdated system-wide installed Eigen library, which is the only reasonable explanation I can think of.

Regarding the error you report on the method `emplace_back`, this method returns a reference since C++17 which is enforced in the CMakeList: https://github.com/ialzugaray/haste/blob/955c80acf6256d1d4fead22e6b11b8e351b34f53/CMakeLists.txt#L6
Please make sure you are compiling the code with C++17/C++20 standard instead of C++11 or older.

**Comment by ialzugaray** [comment]
Closed due to inactivity.
