### ISSUE TITLE
Is the output of HASTE distorted?

### ISSUE THREAD

**Issue by Unsigned-Long** [ialzugaray/haste#7]
Thank you for open-sourcing such an excellent event feature tracking algorithm. I have a question: Does the feature tracking result **output** by `HASTE` **contain** camera **distortion**?
I roughly looked at the code and it seems that the input event data will be dedistorted first, so I guess the output tracking result should be distortion-free. I wonder if my thinking is reasonable? :smile:

**Comment by ialzugaray** [comment]
Hi, thank you for taking interest in our work. 

The code is not distortion aware. It would be able to track distorted data because, in the end, it tracks locally. The performance towards the edges of the image should drop due to distortion (the feature template mismatches the generated data). If you need an undistorted output (and you dont particularly mind that performance to drop due to distortions near edges), you can always undistort the resulting geometric tracks in a post processing step.

**Comment by Unsigned-Long** [comment]
I got it! Thanks for your prompt reply!!! :+1:
